export const MAX_TREE_MEMBERS = 10_000
export const MAX_TREE_RELATED_RECORDS = 20_000
export const MAX_RESPONSE_PAGE_BYTES = 6 * 1024 * 1024
export const DEFAULT_LIST_PAGE_SIZE = 50
export const MAXIMUM_LIST_PAGE_SIZE = 100
export const MINIMUM_SEARCH_LENGTH = 3
